services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: starwarsapp
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uapp", "-papp"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    image: tymkaj/starwarsapp:1.0.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: starwarsapp
      DB_USERNAME: app
      DB_PASSWORD: app
    ports:
      - "8080:8080"

volumes:
  db_data:
